cask "google-chrome"
cask "spotify"
cask "vlc"
cask "logseq"
cask "thunderbird"
cask "macvim"
cask "iterm2"
cask "dash"
cask "karabiner-elements"
cask "bitwarden"
cask "rectangle"
cask "flow"
cask "grammarly"

